name: 'readmissions_lean_input'
version: '0.0.1'
config-version: 2
profile:                       # configuration required: use your dbt profile

vars:
    source_name:               # configuration required
    source_database:           # configuration required
    source_schema:             # configuration required

    src_patient: "{{ source(var('source_name'),'stg_patient') }}"
    src_encounter: "{{ source(var('source_name'),'stg_encounter') }}"
    src_diagnosis: "{{ source(var('source_name'),'stg_diagnosis') }}"
    src_procedure: "{{ source(var('source_name'),'stg_procedure') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  readmissions_lean_input:
    +database:    # configuration required: database where readmissions models will be in
    +schema:      # configuration required: schema where readmissions models will be in

seeds:
  readmissions_lean_input:
    +database:    # configuration required: database where readmissions models will be in  
    +schema: terminology
    +tags: terminology
    +quote_columns: false
    discharge_status_code:
      +column_types: {discharge_status_code: varchar(8)}
    ms_drg:
      +column_types: {ms_drg: varchar(8)}

